-- AlterTable
ALTER TABLE "Clients" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "company_name" DROP NOT NULL,
ALTER COLUMN "add1" DROP NOT NULL,
ALTER COLUMN "add2" DROP NOT NULL,
ALTER COLUMN "post_code" DROP NOT NULL;
