export { HomePage } from './HomePage/HomePage'
export { Dashboard } from './Dashboard/Dashboard/Dashboard'
export { TitleCard } from './HomePage/TitleCard'
export { NavBar } from './Dashboard/NavBar/NavBar'
export { Calender } from './Dashboard/Calender/Calender'
