export { HomePage } from './HomePage/HomePage'
export { Calendar } from './Dashboard/Calendar/Calendar'
export { TitleCard } from './HomePage/TitleCard'
export { NavBar } from './Dashboard/NavBar/NavBar'
export { Calender } from './Dashboard/Calendar/CalenderItems'
export { ClientDetails } from './Dashboard/Clients/ClientsDetails'
export { AddClient } from './Dashboard/Clients/AddClient'
export { PageMenu } from './ui/pageMenu/PageMenu'
